### ISSUE TITLE
Importing 1.9.0 Villagers causes null exception

### ISSUE THREAD

**Issue by KevinCCucumber** [Norviah/animal-crossing#1]
When executing   `npm run build:src && npm run start `, te tool imports all sheets but fails on creating the json files. The only values that are null on the villager spreadsheed are `Furniture List` & `Furniture Name List`, so I assume that this is causing the error.

Error:
![image](https://user-images.githubusercontent.com/49205361/111836529-bbdbab00-88f6-11eb-9316-b9d8674c8a85.png)

```
> animal-crossing@7.3.0 build:src
> ./node_modules/typescript/bin/tsc


> animal-crossing@7.3.0 start
> /bin/rm -rf ./json/combined ./json/data ./json/raw && node ./build/index.js

✔ finished: Editors' Copy - Data Spreadsheet for ACNH
✖ error

An error occurred while converting
Error: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:191970772851'.

Retrying attempt #2 in 30 seconds...

✔ finished: Translations - Updated for 1.9.0
/mnt/d/Programmieren/Repos/Github/animal-crossing/build/util/separate.js:11
    return string.split(separator).map((string) => string.trim());
                  ^

TypeError: Cannot read property 'split' of null
    at Object.separate (/mnt/d/Programmieren/Repos/Github/animal-crossing/build/util/separate.js:11:19)
    at Object.<anonymous> (/mnt/d/Programmieren/Repos/Github/animal-crossing/build/handlers/villagers.js:19:45)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /mnt/d/Programmieren/Repos/Github/animal-crossing/build/index.js:50:57
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! code 1
npm ERR! path /mnt/d/Programmieren/Repos/Github/animal-crossing
npm ERR! command failed
npm ERR! command sh -c /bin/rm -rf ./json/combined ./json/data ./json/raw && node ./build/index.js
```

**Comment by Norviah** [comment]
fixed by this [pull request](https://github.com/Norviah/animal-crossing/pull/2)
